---
sudo: required
os:
  - linux
language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.5.3
addons:
  firefox: latest
before_install:
  - gem update --system
  - gem install bundler
  - bundle update
before_script:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg
  - ffmpeg -hwaccels
  - echo $DISPLAY
