---
sudo: required
os:
  - linux
language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.5.1
before_install:
  - gem update --system
  - gem install bundler
  - bundle update
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - ffmpeg -hwaccels
