---
sudo: required
os:
  - linux
language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.5.1
before_install:
  - gem update --system
  - gem install bundler
  - bundle update
before_script:
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg
  - ffmpeg -hwaccels
