language: ruby
cache: bundler
branches:
  only:
    - /.*/
env:
  global:
    - DISPLAY=":0"
matrix:
  include:
    - rvm: 2.4
      dist: bionic
      env: RAKE_TASK=spec
    - rvm: 2.5
      dist: bionic
      env: RAKE_TASK=spec
    - rvm: 2.6
      dist: bionic
      env: RAKE_TASK=spec REPORT_COVERAGE=true
    - rvm: 2.7
      dist: bionic
      env: RAKE_TASK=rubocop
    - rvm: 2.7
      os: osx
      osx_image: xcode11
      env: RAKE_TASK=spec
    - rvm: jruby-9.2.11.1
      dist: bionic
      jdk: openjdk8
      env: RAKE_TASK=spec JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
      - ffmpeg
  homebrew:
    packages:
      - ffmpeg
before_install:
  - gem update --system -N
  - gem install bundler -N
before_script:
  - bash support/start_xvfb.sh
  - bash support/start_test_reporter.sh
script: bundle exec rake $RAKE_TASK
after_script:
  - bash support/stop_test_reporter.sh
